IFACE = "lo"

# Minimum observation window used to smooth flow rates.
RATE_MIN_WINDOW_SECONDS = 1.0

# Port scan detection tuning
PORT_SCAN_WINDOW_SECONDS = 10
PORT_SCAN_MIN_DISTINCT_PORTS = 5
PORT_SCAN_ALERT_COOLDOWN_SECONDS = 5

# Anomaly detection tuning
ANOMALY_CONTAMINATION = 0.01
ANOMALY_MIN_TRAIN_SAMPLES = 1000
ANOMALY_MAX_TRAIN_SAMPLES = 5000
ANOMALY_REFIT_EVERY = 50
ANOMALY_THRESHOLD_PERCENTILE = 1

# Rolling z-score tuning
PACKET_SIZE_ZSCORE_WINDOW = 100
PACKET_SIZE_ZSCORE_MIN_SAMPLES = 5
PACKET_RATE_ZSCORE_WINDOW = 100
PACKET_RATE_ZSCORE_MIN_SAMPLES = 5
ZSCORE_EPSILON = 1e-6

# Plot dashboard tuning
PLOT_MAX_POINTS = 5000
PLOT_UPDATE_EVERY = 5
PLOT_ANOMALY_RATE_WINDOW = 200